import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";
import { SearchBar } from "./search";
import { Button } from "./button";
import { NotificationBell } from "./icons";

type Props = {
  title: string;
  children: ReactNode;
};

export const MainLayout = ({ title, children }: Props) => {
  const LINKS = [
    "FAQ",
    "Help Center",
    "Account",
    "Media Center",
    "Investor Relations",
    "Jobs",
    "Ways to Watch",
    "Terms of Use",
    "Privacy",
    "Cookie Preferences",
    "Corporate Information",
    "Contact Us",
    "Speed Test",
    "Legal Notices",
    "Only on Netflix",
  ];

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="sticky top-0 flex w-full justify-center">
        <nav className="container mx-12 flex h-16 max-w-screen-2xl items-center justify-between text-[16px] font-medium">
          <div className="flex items-center gap-6">
            <div className="cursor-pointer font-mono text-3xl font-extrabold">
              <Link href="/">
                <Image
                  className="h-auto w-auto"
                  src="/logo.png"
                  alt="logo"
                  width={110}
                  height={35}
                  priority={true}
                />
              </Link>
            </div>
            <div className="hidden gap-6 md:flex">
              <Link href={"/home"}>Home</Link>
              <Link href={"/tv-show"}>Tv Show</Link>
              <Link href={"/new-and-popular"}>New & Popular</Link>
              <Link href={"/my-list"}>My List</Link>
            </div>
          </div>
          <div className="flex items-center gap-6">
            <SearchBar />
            <div className="cursor-pointer active:opacity-70">
              <NotificationBell />
            </div>
            <Button
              icon={null}
              text="Sign In"
              type="netflix"
              handleClick={() => console.log("take to login page")}
            />
          </div>
        </nav>
      </header>

      <main className="flex w-full justify-center">{children}</main>

      <footer className="flex w-full justify-center text-zinc-500">
        <section className="container mx-12 max-w-screen-2xl">
          <p className="container my-4 max-w-screen-2xl text-[15px]">
            Questions? Call{" "}
            <span className="cursor-pointer hover:text-zinc-400 hover:underline active:opacity-70">
              000-000-000-000
            </span>
          </p>
          <section className="container max-w-screen-2xl">
            <ul className="flex max-w-3xl flex-wrap gap-x-12 ">
              {LINKS.map((link) => (
                <li key={link} className="w-[140px] text-[13px] font-light ">
                  <Link
                    className="cursor-pointer transition-all hover:text-zinc-400"
                    href="/"
                  >
                    {link}
                  </Link>
                </li>
              ))}
            </ul>
          </section>
          <p className="mb-8 mt-4 text-[15px]">© Netflix</p>
        </section>
      </footer>
    </>
  );
};
